import pastillas from "@/assets/images/pastillas.jpg";
import frutas from "@/assets/images/frutas.jpg";
import carnes from "@/assets/images/carnes.jpg";
import huevos from "@/assets/images/huevos.jpg";
import panaderia from "@/assets/images/panaderia.jpg";

// PRODUCTOS
import pastillaUno from "@/assets/images/products/pastillauno.jpg";
import pastillaDos from "@/assets/images/products/pastillados.png";
import pastillaTres from "@/assets/images/products/pastillatres.jpg";
import frutaUno from "@/assets/images/products/frutauno.jpg";
import frutaDos from "@/assets/images/products/frutados.png";
import frutaTres from "@/assets/images/products/frutatres.jpg";
import frutaCuatro from "@/assets/images/products/frutacuatro.jpg";
import carneUno from "@/assets/images/products/carneuno.jpg";
import carneDos from "@/assets/images/products/carnedos.jpg";
import carneTres from "@/assets/images/products/carnetres.jpg";
import carneCuatro from "@/assets/images/products/carnecuatro.jpg";
import carneCinco from "@/assets/images/products/carnecinco.jpg";

export const listProducts = {
  data: [
    {
      id: 1,
      image: pastillas,
      name: "Medicamentos de libre distribución",
      description:
        "Productos farmacéuticos de venta libre para el cuidado de la salud y alivio de síntomas comunes",
      products: [
        {
          id: "101",
          is_active: true,
          code: "MED001",
          name: "Paracetamol",
          description: "Analgésico y antipirético para el alivio del dolor y la fiebre",
          image: pastillaUno,
          calification: 2,
          stock: 50,
          normal_unit_price: "10.00",
          unit_price_discount: "8.50",
          created_at: "2024-01-15T00:00:00Z",
          weight: "500 mg",
          brand: {
            id: "brand_generic",
            code: "BG001",
            name: "Genérico",
          },
          category: {
            id: "cat_medicamentos",
            code: "CM001",
            name: "Medicamentos",
          },
          new: false,
        },
        {
          id: "102",
          is_active: true,
          code: "MED002",
          name: "Ibuprofeno",
          description:
            "El ibuprofeno es un derivado del ácido propiónico con propiedades analgésicas (alivia el dolor), antiinflamatorias (reduce la inflamación) y antipiréticas (baja la fiebre) . Su mecanismo de acción principal consiste en inhibir la síntesis de prostaglandinas a nivel periférico . Las prostaglandinas son sustancias químicas que produce el cuerpo y que están asociadas a la sensación de dolor, la respuesta inflamatoria (enrojecimiento, hinchazón) y la aparición de fiebre. Al bloquear su producción, el ibuprofeno consigue aliviar estos síntomas",
          image: pastillaDos,
          calification: 2,
          stock: 30,
          normal_unit_price: "14.00",
          unit_price_discount: "12.00",
          created_at: "2024-01-15T00:00:00Z",
          weight: "400 mg",
          brand: {
            id: "brand_generic",
            code: "BG001",
            name: "Genérico",
          },
          category: {
            id: "cat_medicamentos",
            code: "CM001",
            name: "Medicamentos",
          },
          new: false,
        },
        {
          id: "103",
          is_active: true,
          code: "MED003",
          name: "Aspirina",
          description: "Ácido acetilsalicílico para el dolor y la fiebre",
          image: pastillaTres,
          stock: 25,
          normal_unit_price: "18.50",
          unit_price_discount: "15.75",
          created_at: "2024-01-15T00:00:00Z",
          weight: "500 mg",
          brand: {
            id: "brand_bayer",
            code: "BB001",
            name: "Bayer",
          },
          category: {
            id: "cat_medicamentos",
            code: "CM001",
            name: "Medicamentos",
          },
          new: true,
        },
      ],
    },
    {
      id: 7,
      image: frutas,
      name: "Frutas y Verduras",
      description:
        "Frescos y nutritivos productos del campo, seleccionados para garantizar su calidad y saturalidad",
      products: [
        {
          id: "701",
          is_active: true,
          code: "FRU001",
          name: "Manzanas Rojas",
          description: "Manzanas rojas frescas por kilo",
          image: frutaUno,
          stock: 150,
          normal_unit_price: "4.20",
          unit_price_discount: "3.50",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_fresco",
            code: "BF001",
            name: "Fresco del Campo",
          },
          category: {
            id: "cat_frutas",
            code: "CF001",
            name: "Frutas y Verduras",
          },
          new: true,
        },
        {
          id: "702",
          is_active: true,
          code: "FRU002",
          name: "Plátanos",
          description: "Plátanos maduros por mano",
          image: frutaDos,
          stock: 80,
          normal_unit_price: "3.20",
          unit_price_discount: "2.80",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_tropical",
            code: "BT001",
            name: "Tropical",
          },
          category: {
            id: "cat_frutas",
            code: "CF001",
            name: "Frutas y Verduras",
          },
          new: false,
        },
        {
          id: "703",
          is_active: true,
          code: "FRU003",
          name: "Zanahorias",
          description: "Zanahorias frescas por kilo",
          image: frutaTres,
          stock: 120,
          normal_unit_price: "2.30",
          unit_price_discount: "1.90",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_huerta",
            code: "BH001",
            name: "Huerta Natural",
          },
          category: {
            id: "cat_frutas",
            code: "CF001",
            name: "Frutas y Verduras",
          },
          new: false,
        },
        {
          id: "704",
          is_active: true,
          code: "FRU004",
          name: "Lechuga",
          description: "Lechuga romana fresca",
          image: frutaCuatro,
          stock: 60,
          normal_unit_price: "2.80",
          unit_price_discount: "2.20",
          created_at: "2024-01-15T00:00:00Z",
          weight: "Unidad",
          brand: {
            id: "brand_verde",
            code: "BV001",
            name: "Verde Fresco",
          },
          category: {
            id: "cat_frutas",
            code: "CF001",
            name: "Frutas y Verduras",
          },
          new: false,
        },
      ],
    },
    {
      id: 2,
      image: carnes,
      name: "Carnes y Pescados",
      description:
        "Cortes seleccionados de máxima calidad y pescados frescos para una alimentación saludable",
      products: [
        {
          id: "201",
          is_active: true,
          code: "CAR001",
          name: "Pechuga de Pollo",
          description: "Pechuga de pollo sin hueso",
          image: carneUno,
          stock: 45,
          normal_unit_price: "14.50",
          unit_price_discount: "12.90",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_avicola",
            code: "BA001",
            name: "Avícola Premium",
          },
          category: {
            id: "cat_carnes",
            code: "CC001",
            name: "Carnes y Pescados",
          },
        },
        {
          id: "202",
          is_active: true,
          code: "CAR002",
          name: "Carne Molida",
          description: "Carne molida de res 80/20",
          image: carneDos,
          stock: 30,
          normal_unit_price: "17.80",
          unit_price_discount: "15.50",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_carnes",
            code: "BC001",
            name: "Carnes Selectas",
          },
          category: {
            id: "cat_carnes",
            code: "CC001",
            name: "Carnes y Pescados",
          },
          new: true,
        },
        {
          id: "203",
          is_active: true,
          code: "CAR003",
          name: "Salmón Fresco",
          description: "Filetes de salmón del Atlántico",
          image: carneTres,
          stock: 20,
          normal_unit_price: "32.00",
          unit_price_discount: "28.75",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_mar",
            code: "BM001",
            name: "Mar Fresco",
          },
          category: {
            id: "cat_carnes",
            code: "CC001",
            name: "Carnes y Pescados",
          },
          new: true,
        },
        {
          id: "204",
          is_active: true,
          code: "CAR004",
          name: "Cerdo Lomo",
          description: "Lomo de cerdo para asar",
          image: carneCuatro,
          stock: 25,
          normal_unit_price: "21.00",
          unit_price_discount: "18.40",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_premium",
            code: "BP002",
            name: "Carnes Premium",
          },
          category: {
            id: "cat_carnes",
            code: "CC001",
            name: "Carnes y Pescados",
          },
          new: false,
        },
        {
          id: "205",
          is_active: true,
          code: "CAR005",
          name: "Costillas de res",
          description: "Costillas",
          image: carneCinco,
          stock: 25,
          normal_unit_price: "15.00",
          unit_price_discount: "11.40",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_premium",
            code: "BP002",
            name: "Carnes Premium",
          },
          category: {
            id: "cat_carnes",
            code: "CC001",
            name: "Carnes y Pescados",
          },
          new: false,
        },
      ],
    },
    {
      id: 3,
      image: huevos,
      name: "Lácteos y Huevos",
      description:
        "Productos lácteos frescos y huevos de calidad premium para una nutrición completa",
      products: [
        {
          id: "301",
          is_active: true,
          code: "LAC001",
          name: "Leche Entera",
          description: "Leche entera pasteurizada 1L",
          image: "leche.jpg",
          stock: 100,
          normal_unit_price: "5.50",
          unit_price_discount: "4.80",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 ml",
          brand: {
            id: "brand_lactosa",
            code: "BL001",
            name: "Lactosa",
          },
          category: {
            id: "cat_lacteos",
            code: "CL001",
            name: "Lácteos y Huevos",
          },
          new: false,
        },
        {
          id: "302",
          is_active: true,
          code: "LAC002",
          name: "Queso Mozzarella",
          description: "Queso mozzarella en barra 400g",
          image: "queso-mozzarella.jpg",
          stock: 40,
          normal_unit_price: "25.00",
          unit_price_discount: "22.50",
          created_at: "2024-01-15T00:00:00Z",
          weight: "400 gr",
          brand: {
            id: "brand_quesos",
            code: "BQ001",
            name: "Quesos Selectos",
          },
          category: {
            id: "cat_lacteos",
            code: "CL001",
            name: "Lácteos y Huevos",
          },
          new: true,
        },
        {
          id: "303",
          is_active: true,
          code: "LAC003",
          name: "Huevos Blancos",
          description: "Huevos blancos grade A por docena",
          image: "huevos.jpg",
          stock: 75,
          normal_unit_price: "10.50",
          unit_price_discount: "8.90",
          created_at: "2024-01-15T00:00:00Z",
          weight: "Docena",
          brand: {
            id: "brand_granja",
            code: "BG002",
            name: "Granja Feliz",
          },
          category: {
            id: "cat_lacteos",
            code: "CL001",
            name: "Lácteos y Huevos",
          },
          new: false,
        },
        {
          id: "304",
          is_active: true,
          code: "LAC004",
          name: "Yogurt Natural",
          description: "Yogurt natural sin azúcar 500g",
          image: "yogurt.jpg",
          stock: 60,
          normal_unit_price: "7.80",
          unit_price_discount: "6.50",
          created_at: "2024-01-15T00:00:00Z",
          weight: "500 gr",
          brand: {
            id: "brand_lacteos",
            code: "BL002",
            name: "Lácteos Frescos",
          },
          category: {
            id: "cat_lacteos",
            code: "CL001",
            name: "Lácteos y Huevos",
          },
          new: true,
        },
      ],
    },
    {
      id: 4,
      image: panaderia,
      name: "Panadería y Pastelería",
      description:
        "Deliciosos panes recién horneados y exquisitos postres artesanales para todos los gustos",
      products: [
        {
          id: "401",
          is_active: true,
          code: "PAN001",
          name: "Pan de Molde Integral",
          description: "Pan de molde integral 500g",
          image: "pan-integral.jpg",
          stock: 35,
          normal_unit_price: "9.20",
          unit_price_discount: "7.80",
          created_at: "2024-01-15T00:00:00Z",
          weight: "500 gr",
          brand: {
            id: "brand_panaderia",
            code: "BP003",
            name: "Panadería Artesanal",
          },
          category: {
            id: "cat_panaderia",
            code: "CP001",
            name: "Panadería y Pastelería",
          },
          new: false,
        },
        {
          id: "402",
          is_active: true,
          code: "PAN002",
          name: "Croissants",
          description: "Croissants de mantequilla por 6 unidades",
          image: "croissants.jpg",
          stock: 25,
          normal_unit_price: "14.50",
          unit_price_discount: "12.00",
          created_at: "2024-01-15T00:00:00Z",
          weight: "6 Unidades",
          brand: {
            id: "brand_dulce",
            code: "BD001",
            name: "Dulce Horno",
          },
          category: {
            id: "cat_panaderia",
            code: "CP001",
            name: "Panadería y Pastelería",
          },
          new: false,
        },
        {
          id: "403",
          is_active: true,
          code: "PAN003",
          name: "Torta de Chocolate",
          description: "Torta de chocolate belga 1000 gr",
          image: "torta-chocolate.jpg",
          stock: 8,
          normal_unit_price: "52.00",
          unit_price_discount: "45.00",
          created_at: "2024-01-15T00:00:00Z",
          weight: "1000 gr",
          brand: {
            id: "brand_reposteria",
            code: "BR001",
            name: "Repostería Fina",
          },
          category: {
            id: "cat_panaderia",
            code: "CP001",
            name: "Panadería y Pastelería",
          },
          new: true,
        },
        {
          id: "404",
          is_active: true,
          code: "PAN004",
          name: "Galletas de Avena",
          description: "Galletas de avena y miel 300g",
          image: "galletas-avena.jpg",
          stock: 50,
          normal_unit_price: "6.80",
          unit_price_discount: "5.50",
          created_at: "2024-01-15T00:00:00Z",
          weight: "300 gr",
          brand: {
            id: "brand_snack",
            code: "BS001",
            name: "Snack Natural",
          },
          category: {
            id: "cat_panaderia",
            code: "CP001",
            name: "Panadería y Pastelería",
          },
          new: false,
        },
      ],
    },
  ],
};
